# Generated by Django 5.0.4 on 2024-04-24 16:51

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberAttackCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/cybercategories')),
            ],
            options={
                'verbose_name': 'Cyber_Attack_Category',
                'verbose_name_plural': 'Cyber_Attack_Categories',
                'db_table': 'cyber_attack_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CyberDefenseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/cyberdefensecategories')),
            ],
            options={
                'verbose_name': 'Cyber_Defense_Category',
                'verbose_name_plural': 'Cyber_Defense_Categories',
                'db_table': 'cyber_defense_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CyberAttacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/cyber_attacks')),
                ('context', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cyberattackcategories')),
            ],
            options={
                'verbose_name': 'Cyber_Attack',
                'verbose_name_plural': 'Cyber_Attacks',
                'db_table': 'cyber_attacks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CyberDefenseTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='img/cyber_defense_tools')),
                ('context', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cyberdefensecategories')),
            ],
            options={
                'verbose_name': 'Cyber_Defense_Tool',
                'verbose_name_plural': 'Cyber_Defense_Tools',
                'db_table': 'cyber_defense_tools',
                'ordering': ['name'],
            },
        ),
    ]
