# Generated by Django 5.0.4 on 2024-04-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyberattackcategories',
            old_name='img',
            new_name='image',
        ),
    ]
