# Generated by Django 5.0.4 on 2024-04-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_courses_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='description',
        ),
    ]
