# Generated by Django 5.0.4 on 2024-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lessons_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='image',
            field=models.ImageField(blank=True, upload_to='lessons/'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
