# Generated by Django 5.0.4 on 2024-05-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image',
        ),
    ]
